from __future__ import annotations

from pathlib import Path

import pytest

from elyndra.application import ElyndraApplication
from elyndra.paths import ElyndraPaths
from elyndra.router import DeterministicRouter
from elyndra.web.server import ElyndraWebService


def _executable(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(0o755)
    return path


def _rust_project(root: Path, *, lock: bool = True, tests: bool = True) -> Path:
    root.mkdir(parents=True)
    (root / "Cargo.toml").write_text(
        "[package]\n"
        'name = "demo"\n'
        'version = "0.1.0"\n'
        'edition = "2021"\n\n'
        "[dependencies]\n"
        'serde = "1"\n',
        encoding="utf-8",
    )
    if lock:
        (root / "Cargo.lock").write_text(
            "# This file is automatically @generated by Cargo.\nversion = 3\n",
            encoding="utf-8",
        )
    (root / "src").mkdir()
    (root / "src" / "lib.rs").write_text(
        "pub fn add(a: i32, b: i32) -> i32 { a + b }\n",
        encoding="utf-8",
    )
    if tests:
        (root / "tests").mkdir()
        (root / "tests" / "add.rs").write_text(
            "#[test]\nfn adds() { assert_eq!(demo::add(1, 2), 3); }\n",
            encoding="utf-8",
        )
    return root


def test_rust_router_clarifies_missing_path_and_routes_project() -> None:
    router = DeterministicRouter()

    missing = router.route("rust verify")
    verify = router.route("verifica proyecto Rust /tmp/rust-demo")
    inspect = router.route("inspecciona proyecto Rust /tmp/rust-demo")

    assert missing.kind == "clarification"
    assert missing.params["intended_skill"] == "rust.verify_project"
    assert verify.skill_name == "rust.verify_project"
    assert inspect.skill_name == "rust.project_inspect"


def test_rust_inspect_reports_manifest_without_execution(
    isolated_home: ElyndraPaths,
) -> None:
    project = _rust_project(Path.home() / "Proyectos" / "rust-inspect")
    marker = project / "executed"
    _executable(project / ".venv" / "bin" / "cargo", f"#!/bin/sh\ntouch '{marker}'\n")
    app = ElyndraApplication.load(isolated_home)

    result = app.execute_skill(
        "rust.project_inspect",
        {"path": str(project)},
        approved=True,
    )

    assert result.ok is True
    inventory = result.data["inventory"]
    assert inventory["rust_files"] == 2
    assert inventory["test_files"] == 1
    assert inventory["package"] == "demo"
    assert inventory["edition"] == "2021"
    assert inventory["frameworks"] == ["Serde"]
    assert not marker.exists()


def test_rust_external_project_requires_one_time_authorization(
    isolated_home: ElyndraPaths,
) -> None:
    project = _rust_project(Path.home() / "Escritorio" / "rust-external")
    app = ElyndraApplication.load(isolated_home)

    denied = app.execute_skill(
        "rust.project_inspect",
        {"path": str(project)},
        approved=True,
    )
    allowed = app.execute_skill(
        "rust.project_inspect",
        {"path": str(project), "allow_root_once": True},
        approved=True,
    )

    assert denied.ok is False
    assert "--allow-root-once" in denied.message
    assert allowed.ok is True
    assert allowed.data["authorization_scope"] == "project_once"


def test_rust_manifest_validation_is_deterministic_and_warns_about_build_scripts(
    isolated_home: ElyndraPaths,
) -> None:
    project = _rust_project(Path.home() / "Proyectos" / "rust-manifest")
    (project / "build.rs").write_text("fn main() {}\n", encoding="utf-8")
    marker = project / "cargo-ran"
    _executable(project / ".venv" / "bin" / "cargo", f"#!/bin/sh\ntouch '{marker}'\n")
    app = ElyndraApplication.load(isolated_home)

    result = app.execute_skill(
        "rust.manifest_validate",
        {"path": str(project)},
        approved=True,
    )

    assert result.ok is True
    assert any("build.rs" in item for item in result.data["report"]["warnings"])
    assert not marker.exists()


def test_rustfmt_uses_check_mode_without_writing_files(
    isolated_home: ElyndraPaths,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project = _rust_project(Path.home() / "Proyectos" / "rust-fmt")
    source = project / "src" / "lib.rs"
    before = source.read_text(encoding="utf-8")
    log = Path.home() / "cargo-fmt.log"
    _executable(
        project / ".venv" / "bin" / "cargo",
        f"#!/bin/sh\nprintf '%s\\n' \"$*\" > '{log}'\nexit 0\n",
    )
    monkeypatch.setenv("PATH", "")
    app = ElyndraApplication.load(isolated_home)

    result = app.execute_skill(
        "rustfmt.check",
        {"path": str(project)},
        approved=True,
    )

    assert result.ok is True
    command = log.read_text(encoding="utf-8")
    assert command.startswith("fmt --manifest-path ")
    assert "--all -- --check" in command
    assert source.read_text(encoding="utf-8") == before
    assert result.data["shell"] is False


def test_cargo_commands_use_fixed_offline_locked_arguments_and_temp_target(
    isolated_home: ElyndraPaths,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project = _rust_project(Path.home() / "Proyectos" / "rust-fixed")
    log = Path.home() / "cargo.log"
    _executable(
        project / ".venv" / "bin" / "cargo",
        "#!/bin/sh\n"
        f"printf '%s|%s|%s|%s\\n' \"$*\" \"$CARGO_NET_OFFLINE\" "
        f"\"$CARGO_TARGET_DIR\" \"$RUSTUP_AUTO_INSTALL\" >> '{log}'\n"
        "mkdir -p \"$CARGO_TARGET_DIR\"\n"
        "touch \"$CARGO_TARGET_DIR/marker\"\n"
        "exit 0\n",
    )
    monkeypatch.setenv("PATH", "")
    app = ElyndraApplication.load(isolated_home)

    check = app.execute_skill("cargo.check", {"path": str(project)}, approved=True)
    clippy = app.execute_skill("cargo.clippy", {"path": str(project)}, approved=True)
    tests = app.execute_skill(
        "cargo.test_project",
        {"path": str(project), "feature_mode": "all"},
        approved=True,
    )

    assert check.ok and clippy.ok and tests.ok
    commands = log.read_text(encoding="utf-8")
    assert "check --manifest-path" in commands
    assert "clippy --manifest-path" in commands
    assert "test --manifest-path" in commands
    assert "--offline --locked --color never" in commands
    assert "--all-targets" in commands
    assert "--all-features" in commands
    assert "|true|" in commands
    assert commands.rstrip().endswith("|0")
    forbidden = (" install ", " update ", " fix ", " fetch ", " vendor ")
    assert not any(item in f" {commands} " for item in forbidden)
    for line in commands.splitlines():
        target = Path(line.split("|")[2])
        assert not target.exists()


def test_cargo_stages_skip_without_lockfile_to_avoid_project_writes(
    isolated_home: ElyndraPaths,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project = _rust_project(Path.home() / "Proyectos" / "rust-no-lock", lock=False)
    marker = project / "cargo-ran"
    _executable(project / ".venv" / "bin" / "cargo", f"#!/bin/sh\ntouch '{marker}'\n")
    monkeypatch.setenv("PATH", "")
    app = ElyndraApplication.load(isolated_home)

    result = app.execute_skill("cargo.check", {"path": str(project)}, approved=True)

    assert result.ok is False
    assert result.data["stage_status"] == "unavailable"
    assert "Cargo.lock no existe" in result.message
    assert not marker.exists()
    assert not (project / "Cargo.lock").exists()


def test_rust_verify_persists_partial_history_without_tools(
    isolated_home: ElyndraPaths,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project = _rust_project(Path.home() / "Proyectos" / "rust-history")
    monkeypatch.setenv("PATH", "")
    app = ElyndraApplication.load(isolated_home)

    result = app.execute_skill(
        "rust.verify_project",
        {"path": str(project)},
        approved=True,
    )

    assert result.ok is True
    run = result.data["verification_run"]
    assert run["toolchain"] == "rust"
    assert run["status"] == "partial"
    stages = {item["name"]: item for item in result.data["stages"]}
    assert stages["inspect"]["status"] == "passed"
    assert stages["manifest"]["status"] == "passed"
    assert stages["fmt"]["status"] == "unavailable"
    assert stages["check"]["status"] == "unavailable"


def test_rust_verify_passes_with_controlled_fake_cargo(
    isolated_home: ElyndraPaths,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    project = _rust_project(Path.home() / "Proyectos" / "rust-verify")
    _executable(project / ".venv" / "bin" / "cargo", "#!/bin/sh\nexit 0\n")
    monkeypatch.setenv("PATH", "")
    app = ElyndraApplication.load(isolated_home)

    result = app.execute_skill(
        "rust.verify_project",
        {"path": str(project)},
        approved=True,
    )

    assert result.ok is True
    assert result.data["verification_run"]["status"] == "passed"
    assert all(item["status"] == "passed" for item in result.data["stages"])


def test_rust_profile_and_control_center(isolated_home: ElyndraPaths) -> None:
    project = _rust_project(Path.home() / "Proyectos" / "rust-profile")
    app = ElyndraApplication.load(isolated_home)
    service = ElyndraWebService(app)

    profile = service.save_rust_profile(
        {
            "project_root": str(project),
            "clippy_enabled": False,
            "feature_mode": "all",
            "max_rust_files": 222,
        }
    )
    overview = service.control_overview()
    projects = service.control_projects()

    assert profile["clippy_enabled"] is False
    assert profile["feature_mode"] == "all"
    assert profile["max_rust_files"] == 222
    assert "target" in profile["exclude_paths"]
    assert overview["rust_profiles"] == 1
    assert "rust_verifications" in overview
    assert projects["rust_profiles"][0]["project_root"] == str(project)
    assert len(app.skills.list_all()) == 102
    with app.database.connect() as connection:
        version = connection.execute(
            "SELECT value FROM schema_meta WHERE key = 'schema_version'"
        ).fetchone()[0]
    assert version == "51"


def test_rust_knowledge_package_is_valid(isolated_home: ElyndraPaths) -> None:
    app = ElyndraApplication.load(isolated_home)
    package = Path(__file__).parents[1] / "knowledge-packs" / "rust-modern-basic"

    inspected = app.alexandria_packages.inspect(package)

    assert inspected["package_id"] == "programming.rust.modern-basic"
    assert inspected["domain"] == "programming/rust"
    assert inspected["source_count"] == 1


def test_rust_source_contains_no_install_update_or_fix_commands() -> None:
    source = (
        Path(__file__).parents[1] / "src" / "elyndra" / "skills" / "rust_project.py"
    ).read_text(encoding="utf-8")

    forbidden_argv = (
        '[str(tool.path), "install"',
        '[str(tool.path), "update"',
        '[str(tool.path), "fix"',
        '[str(tool.path), "fetch"',
        '"--allow-dirty"',
    )
    assert not any(item in source for item in forbidden_argv)
